name: 714WebAI
favicon: null
layout_spectrum: 0.6038529186043888
typography_spectrum: 0.3861587147694081
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3636091221123934
  lightness: 0.20126110292039812
  saturation: 0.5091814384795725
  rhythmicContrast: 0.12924426468089223
purpose: []
